version: '3'
services: 
  postgres:
    image: postgres:latest
    environment: 
      - POSTGRES_PASSWORD=postgres_password
  dbhelper:
    depends_on: 
      - postgres
    build: 
      dockerfile: Dockerfile.dev
      context: ./db_helper
    volumes:
      - ./db_helper:/app
    environment: 
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432