apiVersion: apps/v1
kind: Deployment
metadata:
  name: al-predictor-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: alpredictor
  template:
    metadata:
      labels:
        component: alpredictor
    spec:
      containers:
        - name: alpredictor
          image: jnsbr/covidstate-predictor
          env:
            - name: REDIS_HOST
              value: redis-cluster-ip-service
            - name: REDIS_PORT
              value: '6379'
            - name: PGHOST
              value: postgres-cluster-ip-service
            - name: PGUSER
              value: postgres
            - name: PGDATABASE
              value: postgres
            - name: PGPORT
              value: '5432'
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD