apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbhelper-deployment
spec:
  replicas: 1
  restartPolicy: Never
  selector:
    matchLabels:
      component: dbhelper
  template:
    metadata:
      labels:
        component: dbhelper
    spec:
      containers:
        - name: dbhelper
          image: jnsbr/covidstate-dbhelper
          env:
            - name: PGUSER
              value: postgres
            - name: PGHOST
              value: postgres-cluster-ip-service
            - name: PGDATABASE
              value: postgres
            - name: PGPORT
              value: '5432'
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD
