apiVersion: apps/v1
kind: Deployment
metadata:
  name: dl-manager-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      compoment: dlmanager
  template:
    metadata:
      labels:
        compoment: dlmanager
    spec:
      volumes:
        - name: dlmanager-storage
          persistentVolumeClaim:
            claimName: dl-manager-persistent-volume-claim
      containers:
        - name: dlmanager
          image: jnsbr/covidstate-dlmanager
          env:
            - name: REDIS_HOST
              value: redis-cluster-ip-service
            - name: REDIS_PORT
              value: '6379'
            - name: PGHOST
              value: postgres-cluster-ip-service
            - name: PGUSER
              value: postgres
            - name: PGDATABASE
              value: postgres
            - name: PGPORT
              value: '5432'
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD