module.exports = {
  keyAccessToken: 'access_token',
  keyAvailable: 'available',
  keyEmail: 'email',
  keyHostAll: "0.0.0.0",
  keyJwt: 'jwt',
  keyLearner: 'learner',
  keyLocal: 'local',
  keyQueryCounter: 'queryCounter',
  keyQueryFlag: 'queryFlag',
  msgUpdate: 'update',
  routeApi: '/api',
  routeBase: '/',
  routeClassifiers: '/classifiers',
  routeDownload: '/download',
  routeEmail: '/email',
  routeLabel: '/label',
  routeLabels: '/labels',
  routeLogin: '/login',
  routeLogout: '/logout',
  routeMonitor: '/monitor',
  routePassword: '/password',
  routeSignUp: '/signup',
  routeText: '/text',
  routeTexts: '/texts',
  routeUsers: '/users'

};